In [1]:
import numpy as np

np.random.seed(seed=25)

### NumPy Array

- How to create an empty and a full NumPy array?

In [102]:
np.empty((3, 4), dtype=int)

array([[ -283993031,  1072573782,  -234703241,  1072102498],
       [-1569809037,  1072421347,  1639031070,  1071055031],
       [ 1451139547,  1072499256,  -327612686,  1071816389]])

In [103]:
np.full([3, 3], 13, dtype=int)

array([[13, 13, 13],
       [13, 13, 13],
       [13, 13, 13]])

- Create a Numpy array filled with all zeros

In [104]:
np.zeros(2)

array([0., 0.])

- Create a Numpy array filled with all ones

In [105]:
np.ones(2)

array([1., 1.])

- Check whether a Numpy array contains a specified row

In [106]:
array = np.array([[1,2,3], [4,5,6], [7,8,9]])
np.array([44, 55, 66]) in array

False

- How to Remove rows in Numpy array that contains non-numeric values?

In [107]:
array = np.array([[10.5, 22.5, 3.8],
                  [41, np.nan, np.nan]])
array[~np.isnan(array).any(axis=1)]

array([[10.5, 22.5,  3.8]])

- Remove single-dimensional entries from the shape of an array

In [108]:
array = np.zeros((3, 1, 3))
np.squeeze(array)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

- Find the number of occurrences of a sequence in a NumPy array

In [109]:
array = np.array([[3, 1, 2, 1], 
                  [3, 1, 2, 1],
                  [3, 1, 2, 1],
                  [0, 0, 0, 0]])
repr(array).count('3, 1, 2, 1')

3

- Find the most frequent value in a NumPy array

In [118]:
array = np.random.randint(100, size=10)
print(array)
np.bincount(array).argmax()

[13 46 53 62 67  2 44 44 63 45]


44

- Combining a one and a two-dimensional NumPy Array

In [129]:
array_1d = np.arange(5)
print(num_1d)
  
array_2d = np.arange(10).reshape(2,5)
print('\t')
print(num_2d)
print('\t')
for a, b in np.nditer([array_1d, array_2d]):
    print(f'{a}:{b}')

[0 1 2 3 4]
	
[[0 1 2 3 4]
 [5 6 7 8 9]]
	
0:0
1:1
2:2
3:3
4:4
0:5
1:6
2:7
3:8
4:9


- How to add a border around a NumPy array?

In [132]:
array_ones = np.ones((2, 2))
array = np.pad(array_ones, pad_width=1, mode='constant',
               constant_values=0)
array

array([[0., 0., 0., 0.],
       [0., 1., 1., 0.],
       [0., 1., 1., 0.],
       [0., 0., 0., 0.]])

- How to compare two NumPy arrays?

In [136]:
array_one = np.array([[2,2],[3,4]])
array_two = np.array([[1,2],[3,4]])

(array_one == array_two).all()

False

- How to check whether specified values are present in NumPy array? 

In [3]:
array = np.random.randint(100, size=(3,3))
print([55, 60, 70, 55] in array.tolist())

False


- How to get all 2D diagonals of a 3D NumPy array?

In [11]:
array = np.arange(3 * 4 * 4).reshape(3, 4, 4)
diag_array = np.diagonal(array, 
                       axis1 = 1,
                       axis2 = 2)
print(array)
diag_array

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]

 [[32 33 34 35]
  [36 37 38 39]
  [40 41 42 43]
  [44 45 46 47]]]


array([[ 0,  5, 10, 15],
       [16, 21, 26, 31],
       [32, 37, 42, 47]])

- Flatten a Matrix in Python using NumPy

In [12]:
array = np.array([[3, 1], [2, 1]])
array.flatten()

array([3, 1, 2, 1])

- Flatten a 2d numpy array into 1d array

In [14]:
array = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])
array.flatten()

array([1, 2, 3, 2, 4, 5, 1, 2, 3])

- Move axes of an array to new positions

In [18]:
x = np.zeros((2, 3, 4))
print(np.moveaxis(x, 0, -1))
print('\n')
print(np.moveaxis(x, -1, 0))

[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


- Interchange two axes of an array

In [21]:
x = np.array([[1, 2, 3]])
print(x,'\n')
y =  np.swapaxes(x, 0, 1)
print(y)

[[1 2 3]] 

[[1]
 [2]
 [3]]


- NumPy – Fibonacci Series using Binet Formula

In [27]:
a = np.arange(1, 11)
lenA = len(a)

sqrtFive = np.sqrt(5)
alpha = (1 + sqrtFive) / 2
beta = (1 - sqrtFive) / 2

Fn = np.rint(((alpha ** a) - (beta ** a)) / (sqrtFive))
print("The first {} numbers of Fibonacci series are {} . ".format(lenA, Fn))

The first 10 numbers of Fibonacci series are [ 1.  1.  2.  3.  5.  8. 13. 21. 34. 55.] . 


- Counts the number of non-zero values in the array

In [30]:
array = [[5, 6, 7, 9, 0], [11, 23, 55, 0, 11], [0, 0, 0, 1, 3]]

np.count_nonzero(array)

10

- Count the number of elements along a given axis

In [31]:
array = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(np.size(array, 0))
print(np.size(array, 1))

2
4


- Trim the leading and/or trailing zeros from a 1-D array

In [32]:
array = np.array((0, 0, 0, 0, 1, 5, 7, 0, 6, 2, 9, 0, 10, 0, 0))
np.trim_zeros(array)

array([ 1,  5,  7,  0,  6,  2,  9,  0, 10])

- Change data type of given numpy array

In [38]:
array = np.array([10, 20, 30, 40, 50])
print(array.dtype, '\t')
array = array.astype('float64')
print(array.dtype)

int32 	
float64


- Reverse a numpy array

In [40]:
array = np.array([1, 2, 3, 6, 4, 5])
np.flipud(array)

array([5, 4, 6, 3, 2, 1])

- How to make a NumPy array read-only?

In [45]:
array = np.zeros(10)
array[5] = 8
print(array)

array.flags.writeable = False
array[3] = 5

[0. 0. 0. 0. 0. 8. 0. 0. 0. 0.]


ValueError: assignment destination is read-only

### Questions on NumPy Matrix

- Get the maximum value from given matrix

In [48]:
array = np.array([[11, 12, 13],
                  [14, 15, 16],
                  [17, 15, 19],
                  [12, 14, 15]])
np.amax(array)

19

- Get the minimum value from given matrix

In [49]:
np.amin(array)

11

- Find the number of rows and columns of a given matrix using NumPy

In [50]:
array.shape

(4, 3)

- Select the elements from a given matrix

In [55]:
[array[0][i] for i in range(array.shape[1])]

[11, 12, 13]

- Find the sum of values in a matrix

In [56]:
m = np.matrix([[1, 2], [4, 3]])
m.sum()

10

- Calculate the sum of the diagonal elements of a NumPy array

In [59]:
array = np.array([[55, 33, 44],
                  [21, 4, 60],
                  [56, 23, 41]])
np.trace(array)

100

- Adding and Subtracting Matrices in Python

In [61]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[4, 5], [6, 7]])

print(np.add(A, B))
print('\t')
print(np.subtract(A, B))

[[ 5  7]
 [ 9 11]]
	
[[-3 -3]
 [-3 -3]]


- Ways to add row/columns in numpy array

In [63]:
array = np.array([[1, 2, 3], [45, 4, 7], [9, 6, 10]])
add = np.array([1, 2, 3])
result = np.hstack((array, np.atleast_2d(add).T))

In [65]:
result

array([[ 1,  2,  3,  1],
       [45,  4,  7,  2],
       [ 9,  6, 10,  3]])

In [66]:
np.column_stack((array, add))

array([[ 1,  2,  3,  1],
       [45,  4,  7,  2],
       [ 9,  6, 10,  3]])

- Matrix Multiplication in NumPy

In [67]:
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3])
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7])

np.dot(mat1,mat2)

array([[ 63, 320,  83],
       [ 77, 484, 102],
       [ 84, 248, 117]])

- Get the eigen values of a matrix

In [69]:
w, v = np.linalg.eig(np.diag((1, 2, 3)))
w; v

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

- How to Calculate the determinant of a matrix using NumPy?

In [73]:
array = np.array([[50, 29], [30, 44]])
np.linalg.det(array)

1330.0000000000002

- How to inverse a matrix using NumPy

In [74]:
np.linalg.inv(array)

array([[ 0.03308271, -0.02180451],
       [-0.02255639,  0.03759398]])

- How to count the frequency of unique values in NumPy array?

In [75]:
array = np.array([10, 20, 5, 10, 8, 20, 8, 9, 433, 495])
unique, frequency = np.unique(array, return_counts = True)
print("Unique Values:", 
      unique)
print("Frequency Values:",
      frequency)

Unique Values: [  5   8   9  10  20 433 495]
Frequency Values: [1 2 1 2 2 1 1]


- Multiply matrices of complex numbers using NumPy in Python

In [79]:
x = np.array([2+3j, 4+5j])
y = np.array([8+7j, 5+6j])

np.vdot(x, y)

(87-11j)

- Compute the outer product of two given vectors using NumPy in Python

In [80]:
array1 = np.array([6,2])
array2 = np.array([2,5])

np.outer(array1, array2)

array([[12, 30],
       [ 4, 10]])

- Calculate inner, outer, and cross products of matrices and vectors using NumPy

In [86]:
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

print('inner: ', np.inner(x, y))
print('\t')
print('outer: ', np.outer(x, y))
print('\t')
print('cross: ', np.cross(x, y))

inner:  [[17 52]
 [13 62]]
	
outer:  [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
	
cross:  [[-20   4   7]
 [-84  36  20]]


- Compute the covariance matrix of two given NumPy arrays

In [88]:
array1 = np.array([0, 1, 1])
array2 = np.array([2, 2, 1])

cov = np.cov(array1, array2)
cov

array([[ 0.33333333, -0.16666667],
       [-0.16666667,  0.33333333]])

- Convert covariance matrix to correlation matrix using Python

In [92]:
v = np.sqrt(np.diag(cov))
outer_v = np.outer(v, v)
corr = cov / outer_v
corr

array([[ 1. , -0.5],
       [-0.5,  1. ]])

- Compute the Kronecker product of two mulitdimension NumPy arrays

In [95]:
np.kron(array1, array2)

array([0, 0, 0, 2, 2, 1, 2, 2, 1])

- Convert the matrix into a list

In [96]:
array1.tolist()

[0, 1, 1]

### Questions on NumPy Indexing

- Replace NumPy array elements that doesn’t satisfy the given condition

In [97]:
array = np.array([[45.42436315, 52.48558583, 10.32924763],
                  [5.7439979, 50.58220701, 25.38213418]])

array[array > 30.] = 5.25
array

array([[ 5.25      ,  5.25      , 10.32924763],
       [ 5.7439979 ,  5.25      , 25.38213418]])

- Return the indices of elements where the given condition is satisfied

In [101]:
array = np.array([[1, 2, 3], [4, 5, 6]])
b = np.where(array<4)
print(array[b])

[1 2 3]


- Replace NaN values with average of columns

In [102]:
array = np.array([[1.3, 2.5, 3.6, np.nan],
                  [2.6, 3.3, np.nan, 5.5],
                  [2.1, 3.2, 5.4, 6.5]])

col_mean = np.nanmean(array, axis = 0)
inds = np.where(np.isnan(array))
array[inds] = np.take(col_mean, inds[1])
array

array([[1.3, 2.5, 3.6, 6. ],
       [2.6, 3.3, 4.5, 5.5],
       [2.1, 3.2, 5.4, 6.5]])

- Replace negative value with zero in numpy array

In [104]:
array = np.array([1, 2, -3, 4, -5, -6])
array[array<0] = 0
array

array([1, 2, 0, 4, 0, 0])

- How to get values of an NumPy array at certain index positions?

In [106]:
a1 = np.array([11, 10, 22, 30, 33])
a2 = np.array([1, 15, 60])
a1.put([0, 4], a2)
a1

array([ 1, 10, 22, 30, 15])

- Find indices of elements equal to zero in a NumPy array

In [107]:
array = np.array([1, 0, 2, 0, 3, 0, 4, 5, 6, 7, 8])
np.where(array == 0)[0]

array([1, 3, 5], dtype=int64)

- How to Remove columns in Numpy array that contains non-numeric values?

In [109]:
x = np.array([[1,2,3], [4,5,np.nan], [7,8,9]])
x[~np.isnan(x).any(axis=1)]

array([[1., 2., 3.],
       [7., 8., 9.]])

- How to access different rows of a multidimensional NumPy array?

In [110]:
array = np.array([[10, 20, 30], 
                  [40, 5, 66], 
                  [70, 88, 94]])
array[[0,2]]

array([[10, 20, 30],
       [70, 88, 94]])

- Get row numbers of NumPy array having element larger than X

In [115]:
X = 50
np.where(np.any(array > X, axis = 1))

(array([1, 2], dtype=int64),)

- Get filled the diagonals of NumPy array

In [117]:
np.fill_diagonal(array, 5)
array

array([[ 5, 20, 30],
       [40,  5, 66],
       [70, 88,  5]])

- Check elements present in the NumPy array

In [118]:
print(5 in array)
print(100 in array)

True
False


- Combined array index by index

In [131]:
array = np.array([1, 3, 6, 8, 9, 9, 4, 5]) 
array[np.array([3, 1, 2 ])]

array([8, 3, 6])

### Questions on NumPy Linear Algebra

- Find a matrix or vector norm using NumPy

In [4]:
mat = np.array([[ 1, 2, 3],
               [4, 5, 6]])
np.linalg.norm(mat)

9.539392014169456

- Calculate the QR decomposition of a given matrix using NumPy

In [5]:
q, r = np.linalg.qr(mat)
print('\nQ:\n', q)
print('\nR:\n', r)


Q:
 [[-0.24253563 -0.9701425 ]
 [-0.9701425   0.24253563]]

R:
 [[-4.12310563 -5.33578375 -6.54846188]
 [ 0.         -0.72760688 -1.45521375]]


- Compute the condition number of a given matrix using NumPy

In [6]:
np.linalg.cond(mat)

12.302245504069205

- Compute the eigenvalues and right eigenvectors of a given square array using NumPy?

In [9]:
m = np.array([[1, 2],
              [2, 3]])

w, v = np.linalg.eig(m)
  
print("Printing the Eigen values of the given square array:\n",
      w)

print("Printing Right eigenvectors of the given square array:\n",
      v)

Printing the Eigen values of the given square array:
 [-0.23606798  4.23606798]
Printing Right eigenvectors of the given square array:
 [[-0.85065081 -0.52573111]
 [ 0.52573111 -0.85065081]]


- Calculate the Euclidean distance using NumPy

In [10]:
p1 = np.array((1, 2, 3))
p2 = np.array((1, 1, 1))

np.linalg.norm(p1 - p2)

2.23606797749979

### Questions on NumPy Random

- Create a Numpy array with random values

In [18]:
array = np.random.rand(3,2)
array

array([[0.95854024, 0.76231752],
       [0.32000713, 0.79158141],
       [0.48952105, 0.29635068]])

- How to choose elements from the list with different probability using NumPy?

In [20]:
np.random.choice(array.flatten())

0.29635068449949553

- How to get weighted random choice in Python?

In [25]:
np.random.choice(array.flatten(), 1, p=[0.05, 0.1, 0.15, 0.20, 0.3, 0.2])

array([0.32000713])

- Generate Random Numbers From The Uniform Distribution using NumPy

In [26]:
np.random.uniform(size=4)

array([0.71008104, 0.50138233, 0.9738152 , 0.7528597 ])

- Get Random Elements form geometric distribution

In [28]:
np.random.geometric(p=0.35, size=15)

array([3, 1, 2, 2, 2, 1, 1, 1, 1, 2, 3, 2, 1, 3, 1])

- Get Random elements from Laplace distribution

In [29]:
np.random.laplace(1.45, 15, 15)

array([-24.08379414,  -4.48853484,   1.60299231, -13.03225977,
        22.78479509, -16.98216759,   6.91797974,  36.23156237,
       -15.16239488, -29.88381129,  14.90579377,  -6.30035714,
         3.21387979,  15.80052532,   5.95382705])

- Return a Matrix of random values from a uniform distribution

In [30]:
np.random.uniform(-1,0,15)

array([-0.48554637, -0.0906139 , -0.40017055, -0.07783704, -0.57308426,
       -0.9437696 , -0.9100575 , -0.77101653, -0.44552438, -0.23364622,
       -0.43879821, -0.04926533, -0.23958742, -0.38791139, -0.55525574])

- Return a Matrix of random values from a Gaussian distribution

In [34]:
np.random.normal(3, 2.5, size=(2, 4))

array([[1.92810953, 5.4913243 , 5.42983194, 5.32206503],
       [2.4636665 , 6.8334246 , 0.3148297 , 4.56308196]])

### Questions on NumPy Sorting and Searching

- How to get the indices of the sorted array using NumPy in Python?

In [35]:
array = np.array([10, 52, 62, 16, 16, 54, 453])
np.argsort(array)

array([0, 3, 4, 1, 5, 2, 6], dtype=int64)

- Finding the k smallest values of a NumPy array

In [37]:
k = 4
array1 = np.sort(array)
array1[:k]

array([10, 16, 16, 52])

- How to get the n-largest values of an array using NumPy?

In [39]:
sorted_array = array[np.argsort(array)]
n = 3
sorted_array[-n: ]

array([ 54,  62, 453])

- Sort the values in a matrix

In [45]:
a = np.array([[1,4], [3,1]])
a.sort(axis=1)
print("\n", a, "\n")
a.sort(axis=0)
print("\n", a, "\n")


 [[1 4]
 [1 3]] 


 [[1 3]
 [1 4]] 



- Filter out integers from float numpy array

In [46]:
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])
array[array != array.astype(int)]

array([1.2, 2.2])

- Find the indices into a sorted array

In [48]:
np.searchsorted(array, 3)

6

### Questions on NumPy Mathematics